### ISSUE TITLE
add R package: WeightIt

### ISSUE THREAD

**Issue by JamesAFarrell** [opensafely-core/r-docker#105]
Could the WeightIt package please be added? It has multiple methods for weighting observations. Thanks!
https://cran.r-project.org/web/packages/WeightIt/index.html

**Comment by ghickman** [comment]
@JamesAFarrell – @wjchulme has helpfully pointed out that this will only work with packages hosted on CRAN for the purposes of our image, will that still be of use to you?

**Comment by JamesAFarrell** [comment]
Hi @ghickman and @wjchulme, I think so but not 100% sure.

My analysis is based on this example which only requires WeightIt and cobalt packages:
https://cran.r-project.org/web/packages/cobalt/vignettes/cobalt.html#using-cobalt-with-multi-category-treatments

`WeightIt::weightit(race ~ cov.mn, data = lalonde,
                               method = "ps", use.mlogit = FALSE)`

**Comment by ghickman** [comment]
Thanks @JamesAFarrell, that sounds like it should be fine for this then.
