### ISSUE TITLE
add R package: MASS

### ISSUE THREAD

**Issue by JamesAFarrell** [opensafely-core/r-docker#108]
Hi, could the R package MASS please be added? It has a range of useful functions. For my analysis, I would like it for negative binomial regression (glm.nb). Thanks!
https://cran.r-project.org/web/packages/MASS/index.html

**Comment by wjchulme** [comment]
`MASS` is already installed -- you can view all available packages [here](https://github.com/opensafely-core/r-docker/blob/master/packages.csv)
