### ISSUE TITLE
request for adding packages, please

### ISSUE THREAD

**Issue by rriefu** [opensafely-core/r-docker#115]
Hi, I was wondering if these two packages could be added :

1. https://cran.microsoft.com/snapshot/2022-02-03/web/packages/randomForest/ (updated)
2. https://cran.r-project.org/web/packages/randomForestExplainer/index.html

These two packages are about random forest and we need them in our analyses. Thank you.

**Comment by rriefu** [comment]
@remlapmot  thanks for checking. I've updated the link you provided.

**Comment by rebkwok** [comment]
These packages (with the suggested versions) have been installed now.
