### ISSUE TITLE
ggfortify package

### ISSUE THREAD

**Issue by rzepnk** [opensafely-core/r-docker#119]
Hello. 
Could I please request package ggfortify to be installed. I need it to visualize some of our statistical results and survival models. 

https://cran.r-project.org/web/packages/ggfortify/index.html 

Thanks
Klaudia

**Comment by StevenMaude** [comment]
@rzepnk: :wave: I've just added the ggfortify package to the R image. If you update to the latest R Docker image with `opensafely pull`, you should be able to use it.
