### ISSUE TITLE
add package: gt and gtsummary

### ISSUE THREAD

**Issue by wjchulme** [opensafely-core/r-docker#12]
`gt` is an experimental RStudio package, see https://gt.rstudio.com/.
 `gtsummary` develops it a bit further, see http://www.danieldsjoberg.com/gtsummary/index.html

They're useful for nicely outputting data.frames to html. Both are on CRAN.

**Comment by bloodearnest** [comment]
gt installed fine, but gtsummary failed to build
```
ERROR: dependency 'gert' is not available for package 'usethis'
* removing '/usr/local/lib/R/site-library/usethis'
ERROR: dependency 'usethis' is not available for package 'broom.helpers'
* removing '/usr/local/lib/R/site-library/broom.helpers'
ERROR: dependencies 'broom.helpers', 'usethis' are not available for package 'gtsummary'
* removing '/usr/local/lib/R/site-library/gtsummary'

The downloaded source packages are in
	'/tmp/RtmpJtsgK3/downloaded_packages'
Warning messages:
1: In install.packages("gtsummary") :
  installation of package 'gert' had non-zero exit status
2: In install.packages("gtsummary") :
  installation of package 'usethis' had non-zero exit status
3: In install.packages("gtsummary") :
  installation of package 'broom.helpers' had non-zero exit status
4: In install.packages("gtsummary") :
  installation of package 'gtsummary' had non-zero exit status
```

**Comment by bloodearnest** [comment]
Ah, we need a dependency
----------------------------- ANTICONF -------------------------------
Configuration failed to find libgit2 library. Try installing:
 * brew: libgit2 (MacOS)
 * deb: libgit2-dev (Debian, Ubuntu, etc)
 * rpm: libgit2-devel (Fedora, CentOS, RHEL)
If libgit2 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libgit2.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: git2.h: No such file or directory
compilation terminated.
----------------------------------------------------------------------

**Comment by wjchulme** [comment]
`gtsummary` can wait

**Comment by bloodearnest** [comment]
Have added gt, but not gtsummary yet

**Comment by mbfons** [comment]
Great to have `gt` ! Just to comment that both `gt` and `gtsummary` would come in handy to a repo I'd been working on - so thanks for opening the issue.
