### ISSUE TITLE
add package: rpart.plot

### ISSUE THREAD

**Issue by rriefu** [opensafely-core/r-docker#130]
Hi, could you help add this R package "rpart.plot", please?  -this is to illustrate the result of the existing package "rpart", thanks!
https://cran.r-project.org/web/packages/rpart.plot/index.html

**Comment by remlapmot** [comment]
This seems to go in fine at its current version
```bash
 just add-package rpart.plot
```

**Comment by wjchulme** [comment]
This can be added
