### ISSUE TITLE
Add rdrobust package

### ISSUE THREAD

**Issue by alschaffer** [opensafely-core/r-docker#136]
@opensafely-core/data-team 

I would like to request the package _rdrobust_ be added [https://cran.r-project.org/web/packages/rdrobust/index.html](https://cran.r-project.org/web/packages/rdrobust/index.html).

This package facilitates regression discontinuity analysis, an approach to evaluate the effectiveness of COVID-19 vaccines. As this method requires person-level data or small counts, it must be used within the OpenSAFELY environment.

**Comment by wjchulme** [comment]
This can be added!
