### ISSUE TITLE
Add epitools package please

### ISSUE THREAD

**Issue by AlexOrlek** [opensafely-core/r-docker#137]
https://cran.r-project.org/web/packages/epitools/epitools.pdf
Various epidemiology functions
I'm using the package for risk ratio estimation and confidence intervals

An alternative package if preferred is epiR
https://cran.r-project.org/web/packages/epiR/epiR.pdf

**Comment by StevenMaude** [comment]
@wjchulme had some thoughts on this package, before we consider adding it.

**Comment by AlexOrlek** [comment]
@StevenMaude do you know if a decision has been made on adding the package?

**Comment by wjchulme** [comment]
Hi Alex I got in touch with you about this on Slack shortly after you posted. Would it be easier if I email you?

**Comment by AlexOrlek** [comment]
Hi Will, I picked up the slack message just now, email is better for me, but I'll be online on slack today as well

**Comment by wjchulme** [comment]
Hi , after chatting with @AlexOrlek, happy for EpiTools to be added

**Comment by AlexOrlek** [comment]
Hi @wjchulme, I just wanted to check this is in progress? Do you know how long it will take for it to be added? Thanks.
