### ISSUE TITLE
Add the `twopartm` package please

### ISSUE THREAD

**Issue by liang-yu12** [opensafely-core/r-docker#138]
Hello, could you please install the `twopartm` package? 

- Package name: `twopartm`

- CRAN page: https://cran.r-project.org/web/packages/twopartm/index.html

- Explanation: The package is used for running a two-part model for our study estimating the healthcare utilisation and expenditure of people with long COVID.

**Comment by wjchulme** [comment]
👍🏻

**Comment by StevenMaude** [comment]
@liang-yu12: :wave: The `twopartm` package should now be available to use.

**Comment by liang-yu12** [comment]
Thank you so much! 👍
