### ISSUE TITLE
glmmTMB package 

### ISSUE THREAD

**Issue by sophie-julian** [opensafely-core/r-docker#158]
Hi there, is it possible to install glmmTMB package please? 

CRAN Link: https://cran.r-project.org/web/packages/glmmTMB/index.html 

We are using this package for MAIHDA framework, see example code: https://strengejacke.github.io/ggeffects/articles/practical_intersectionality.html 

We have used this package locally to build one model and have just pushed to github and received this error: Error in library(glmmTMB) : there is no package called ‘glmmTMB’ 

Thank you!

**Comment by bloodearnest** [comment]
@wjchulme thoughts?

**Comment by wjchulme** [comment]
Looks good to me

**Comment by sophie-julian** [comment]
Hi, alongside installing glmmTMB is it possible to have ggeffects (https://cran.r-project.org/web/packages/ggeffects/index.html) and datawizzard (https://cran.r-project.org/web/packages/datawizard/index.html) please? 

This is for the same MAIHDA analysis.

**Comment by bloodearnest** [comment]
Hi @sophie-julian 

We have added glmmTMB to the R image. If you run `opensafely pull`, it should pull the new version of the R image down for you to try locally.

Unfortunately, we couldn't add ggeffects or datawizard, as they both required much newer versions of some dependencies than the R image currently has.  We are aware that this is a limitation of the current R image, and we have plans to fix at some point, involving releasing a new version of the R image with more up to date libraries.

**Comment by sophie-julian** [comment]
Hi @bloodearnest 

Thank you for adding glmmTMB! On the other packages, would you be able to advise on if there's a timeframe for this fix, our code is ready now so would be useful to know if this is expected in the near future?
