### ISSUE TITLE
Adding astsa/forecast/sweep/timetk/doBy packages

### ISSUE THREAD

**Issue by markdrussell** [opensafely-core/r-docker#163]
Hello!

I am setting up a new project that use ARIMA to forecast disease incidence rates pre- vs. post-COVID. This will be based upon the following code:

https://gitlab.com/envhe/wales-cec-ltc-incidence-shiny-dashboard/-/blob/main/sarima_Incidence_rates_18May2022.R?ref_type=heads

I have adapted this code and so that it works locally on my device. However, it requires the following packages, which I don't believe are currently available in the R docker image (please correct me if wrong!):

https://cran.r-project.org/web/packages/astsa/index.html
https://cran.r-project.org/web/packages/sweep/index.html
https://cran.r-project.org/web/packages/timetk/index.html
https://cran.r-project.org/web/packages/forecast/index.html
https://cran.r-project.org/web/packages/doBy/index.html

Would it be possible to have these packages added? Apologies in advance - I'm not an R expert (usually a Stata user), but the R setup for ARIMA is much better than in Stata.

Many thanks,
Mark

**Comment by rebkwok** [comment]
@wjchulme has confirmed these packages are OK to add

**Comment by remlapmot** [comment]
Apologies for the delay @markdrussell. 

It's proving tricky to add these packages to the current r image.

Just to check - do you need all of these packages - I ask because they come with alot of dependencies.

To be able to add these packages conveniently, we're going to have to update the r image, including the version of R and all the other packages. So that will take us a bit more time (sorry I can't be concrete).

**Comment by markdrussell** [comment]
Hi Tom,

Thanks for the update. 

Unfortunately, I think all of the packages are required for the code to run. I have tried to sequentially removing each package, but it doesn't run successfully when I do. 

I've attached a link to the code below. I'm not usually an R user, so you'd be very welcome to have a quick look too. The relevant code is up to line 305.

https://github.com/markdrussell/disease_incidence/blob/main/analysis/200_sarima.R

Best wishes,
Mark

**Comment by remlapmot** [comment]
Hi Mark - we've managed to get these into the existing image. So the new r image will be available shortly. I'll try to message when it's been pushed up to our Docker repository.

**Comment by remlapmot** [comment]
Hi Mark, it should be there now; so if you
```
opensafely pull
```
you'll have those packages. For several of them I couldn't get the latest versions into the image so hopefully the versions added are sufficient for you.

**Comment by markdrussell** [comment]
Brilliant - thanks very much indeed, Tom - really appreciate it.

Best wishes,
Mark

**Comment by markdrussell** [comment]
Hi @remlapmot.

I'm just trying to run my R script via the updated R docker image. When I do so, I get the following error:

     _Error in library(doBy) : there is no package called â€˜doByâ€™
     Execution halted_

The same error occurs when I try to load the next package:

     _Error in library(astsa) : there is no package called â€˜astsaâ€™
     Execution halted_

Do you by any chance know what I am doing wrong?

For reference, the first set of packages I run, seem to load ok:
library(dplyr)
library(ggplot2)
library(fs)
library(zoo)
library(svglite)
library(here)

The issue arises when I try to load the new packages:
library(doBy)
library(astsa)
library(sweep)
library(forecast)
library(timetk)

Thanks,
Mark

**Comment by remlapmot** [comment]
Apologies Mark, something seems to have gone awry with the push to our Docker repo. We will fix tomorrow.

**Comment by remlapmot** [comment]
Hi Mark, the updated Docker image has just been pushed to our repo, so if you run 
```sh
opensafely pull
```
it really will be there this time.

**Comment by markdrussell** [comment]
Brilliant - that's worked a treat. Thanks Tom!
