### ISSUE TITLE
grab installed packages

### ISSUE THREAD

**Issue by wjchulme** [opensafely-core/r-docker#2]
The following code returns a matrix decribing the installed base+external packages. 

``` r
unname(installed.packages()[,c("Package","Version")])
```

Run after the packages have been installed for the build and save / print the output somewhere.

**Comment by wjchulme** [comment]
Adding this line to `Dockerfile` will print a csv to wherever the working directory is 

```r
RUN R -e 'write.csv(installed.packages()[, c("Package","Version")], row.names=FALSE, file="available_packages.csv")'
```

which is a good enough solution for now

**Comment by bloodearnest** [comment]
So, I've attempted to fix this via using conda here: https://github.com/opensafely/r-docker/tree/conda-packages

This works, but is stuck with R 3.6. Trying 4.0 broke a bunch of things, so parking this for now.

**Comment by wjchulme** [comment]
workaround available here https://docs.opensafely.org/en/latest/requests-packages/#requesting-additional-r-packages
