### ISSUE TITLE
Add ehahelper package

### ISSUE THREAD

**Issue by acagreen17** [opensafely-core/r-docker#38]
@bloodearnest , not sure how easy it is (/if we're allowed) to add packages outside of the ones posted on cran. But would be really useful if the `ehahelper` package could be added. 

It helps works with the outputs from the coxme package.

https://github.com/junkka/ehahelper (I installed locally using devtools: `devtools::install_github('junkka/ehahelper')`)

**Comment by bloodearnest** [comment]
The current R image doesn't support using devtools to install, so this was closed.
