### ISSUE TITLE
suggestion: policy for updating the version of R

### ISSUE THREAD

**Issue by remlapmot** [opensafely-core/r-docker#45]
Have you thought about how often or when you will update the version of R within the Docker container?

I ask because R 4.1.0 is released today.

R sort of follows semantic versioning, so in that grammar this is a minor release, but in fact this version does bring some new syntax to the R language (native pipe and lambda functions). I don't need any of those features; but maybe this is worth thinking about.

**Comment by bloodearnest** [comment]
The rough plan would be a separte R 4.1 image that you would use like so in your project.yaml:

 ```
    run: r:4.1 analysis/action.R
```
And we may retag the current :latest docker image as r:4.0, perhaps

**Comment by remlapmot** [comment]
Closing as #123 makes progress towards this.
