### ISSUE TITLE
add package ggalluvial

### ISSUE THREAD

**Issue by rwillans** [opensafely-core/r-docker#57]
Hi,

There doesn't appear to be a package in the list for creating sankey or alluvial visualisations in R. Could we install ggalluvial (https://cran.r-project.org/web/packages/ggalluvial/vignettes/ggalluvial.html)? 

ggsankey will do similar as an alternative if there's an issue with ggalluvial.

Thanks,

Rob

**Comment by bloodearnest** [comment]
Added in #58
