### ISSUE TITLE
add package rms

### ISSUE THREAD

**Issue by RochelleKnight** [opensafely-core/r-docker#62]
Please could the rms package be added

https://cran.r-project.org/web/packages/rms/#:~:text=CRAN%20-%20Package%20rms%20Regression%20modeling%2C%20testing%2C%20estimation%2C,of%20functions%20that%20assist%20with%20and%20streamline%20modeling.

**Comment by bloodearnest** [comment]
I have added rms and published the image. You should be able to do `opensafely pull` to get the latest version locally.
