### ISSUE TITLE
add package finalfit

### ISSUE THREAD

**Issue by JamesAFarrell** [opensafely-core/r-docker#64]
Could the finalfit package please be added? I find this useful for generating quick regression results tables and plots. Thanks!
https://cran.r-project.org/web/packages/finalfit/index.html

**Comment by v1kki213** [comment]
Can I also request this package for generating quick tables. Thanks
Or the tableone package: https://cran.r-project.org/web/packages/tableone/index.html 
both packages are really easy to use and generate tables quickly - great for generating baseline table statistics. 
@sebbacon @madwort @bloodearnest
