### ISSUE TITLE
Add magick package

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/r-docker#67]
Requested in this [Discussions post](https://github.com/opensafely/documentation/discussions/610) by @ciaranmci:

> My analysis script makes use of an [R package called magick](https://cran.r-project.org/web/packages/magick/vignettes/intro.html). When I run my files locally, an error is thrown saying <there is no package called 'magick'>.
I assume magick hasn't been installed.
**Please, can the magick package be installed?**

**Comment by bloodearnest** [comment]
added in #72
