### ISSUE TITLE
dplyr::mutate(dplyr::case_when()) erroring on server by not locally

### ISSUE THREAD

**Issue by ciaranmci** [opensafely-core/r-docker#77]
My error is with the dplyr::mutate( [dplyr::case_when()](https://dplyr.tidyverse.org/reference/case_when.html) ) call.
The error from the job server says that "x must be a logical vector, not a `Date` object". This error doesn't arise when I run on my local machine or locally on my OpenSAFELY docker container.

My R syntax is:
```
mutate(
      date_death = case_when(
                             is.na(.$date_death_ons) & !is.na(.$date_death_cpns) ~ .$date_death_cpns,
                             is.na(.$date_death_cpns) & !is.na(.$date_death_ons) ~ .$date_death_ons,
                             is.na(.$date_death_ons) & is.na(.$date_death_cpns) ~ NA_Date_
                             )
      )
```

The error occured in a [recent job run](https://jobs.opensafely.org/university-of-leeds/cancer-surgery-service-evaluation/all_cause_mortality_with_stratification/6115/rkbgjwd6a3lczzwt/) (ID: rkbgjwd6a3lczzwt)

Any ideas what might be causing the error? I'm really keen to have this output ready for the showcase on April 7th.
Thanks for any help you can offer.

**Comment by bloodearnest** [comment]
@wjchulme @milanwiedemann perhaps you can help Ciaran out here?

**Comment by ciaranmci** [comment]
I think I fixed it with some help from @LFISHER7. I think @wjchulme is the "Will" referred to in the help.
Essentially, "date_death_cpns is all NA. Unless you tell it otherwise, readr() (or similar) will import a column of NAs as a logical vector, so date_death_cpns will be logical. case_when() is strict about mixed vector types, so will give an error when you try to combine a logical with a date".

So, I explicitly declared date_death_cpns as a date and now everything works.
Thanks, all
