### ISSUE TITLE
flexdashboard

### ISSUE THREAD

**Issue by eparker12** [opensafely-core/r-docker#85]
If possible, the flexdashboard R package would be a helpful addition.

**Comment by wjchulme** [comment]
Hi Ed, is it possible for you to extract the data you need for the dashboard using the usual release process, then create the dashboard locally? This would make incremental development easier, avoids complicated disclosure risk checking that would be required for interactive dashboards.

**Comment by eparker12** [comment]
Hi Will. Thanks for looking into this. Yes there would be no problem going with this route. The dashboard is purely for aesthetics - e.g. allowing tabs in the html output that would otherwise require a lengthy linear document. 

But I can see how this complicates disclosure checking (e.g. if an important tab were missed), so am happy to render the dashboards after release instead.

**Comment by wjchulme** [comment]
Tabbing html output is a good idea, will try to do similar for future VE reports!
