### ISSUE TITLE
add package 'consort'

### ISSUE THREAD

**Issue by JamesAFarrell** [opensafely-core/r-docker#87]
Could the 'consort' package please be added? This is useful for generating quick consort diagrams. Thanks
https://cran.rstudio.com/web/packages/consort/index.html

**Comment by wjchulme** [comment]
@bloodearnest this is lightweight and fine to add

@JamesAFarrell in theory this is data that could be released as a csv, and then you can use you local R installation to make the flowchart with consort. Obviously the csv would need to be approriately redacted / rounded for disclosure control. It could also make minor edits to the flowchart easier if there are unexpected formatting differences between the flowchart on dummy data versus real data.  But if it's easy to do, then it's shouldn't be a problem to add to the R image
