### ISSUE TITLE
riskRegression package

### ISSUE THREAD

**Issue by yinghuiwei** [opensafely-core/r-docker#96]
Could you install this package, please?
https://cran.r-project.org/web/packages/riskRegression/index.html

**Comment by wjchulme** [comment]
@opensafely-core/data-team this package can be added

**Comment by evansd** [comment]
This was actually already installed, but must have been pulled in as a dependency of an other package and hence was not listed in `packages.txt`:
https://github.com/opensafely-core/r-docker/blob/cd1857a5d1339ea2b061783d21195b6a1da0517c/packages.csv#L289
