### ISSUE TITLE
R Survey Package

### ISSUE THREAD

**Issue by Miriam-S-git** [opensafely-core/r-docker#97]
https://cran.r-project.org/web/packages/survey/survey.pdf

Dear Team, 

Please could this package be added.  I hope to use it to do Inverse Probability Weighting as a sensitivity analysis for my study.  

http://cran.fhcrc.org/web/packages/survey/index.html

Many Thanks, 

M

**Comment by evansd** [comment]
@wjchulme Could I ask you to cast your eye over this one?

**Comment by wjchulme** [comment]
@opensafely-core/data-team yep this is ok to add
