### ISSUE TITLE
R package - pec

### ISSUE THREAD

**Issue by yinghuiwei** [opensafely-core/r-docker#98]
library(pec)

Can you please install this package? https://cran.r-project.org/web/packages/pec/index.html

**Comment by wjchulme** [comment]
@opensafely-core/data-team this package is fine to add

**Comment by evansd** [comment]
This was actually already installed, but must have been pulled in as a dependency of an other package and hence was not listed in `packages.txt`:
https://github.com/opensafely-core/r-docker/blob/cd1857a5d1339ea2b061783d21195b6a1da0517c/packages.csv#L248
